### ISSUE TITLE
Detail of ProPara Dataset

### ISSUE THREAD

**Issue by XingLuxi** [aditya2211/transformer-entity-tracking#3]
https://github.com/aditya2211/transformer-entity-tracking/blob/d83e6e606141e69baa669fd30fbd688424d96bad/gpt-entity-tracking/get_propara_data_gpt.py#L5

Hi, where can we get the train/dev/test set of ProPara?

**Comment by aditya2211** [comment]
Updated the readme to contain the link for dataset download. You can find the ProPara dataset in 
`bert-entity-tracking/dataset/{train/val/test}_propara_gpt_whole.json`
